version: '3.1'

services:
  php:
    build: ./docker/php/
    network_mode: host
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
